server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: "true"
        show_sql: "true"
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:h2-db
    driverClassName: org.h2.Driver
    username: user
    password: password
  h2:
    console.enabled: true
