DROP TABLE IF EXISTS users CASCADE;


CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    email      VARCHAR(512)                            NOT NULL UNIQUE,
    password   VARCHAR(512)                            NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE             NOT NULL,

    CONSTRAINT pk_user PRIMARY KEY (id)
);