CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    email      VARCHAR(512)                            NOT NULL UNIQUE,
    password   VARCHAR(512)                            NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE             NOT NULL,

    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS quotes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content    VARCHAR(3000)                           NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_on TIMESTAMP WITHOUT TIME ZONE,
    speaker_id BIGINT                                  NOT NULL,

    CONSTRAINT pk_quote PRIMARY KEY (id),
    FOREIGN KEY (speaker_id) REFERENCES users
);

CREATE TABLE IF NOT EXISTS votes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    positive   BOOLEAN                                 NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    voter_id   BIGINT                                  NOT NULL,
    quote_id   BIGINT                                  NOT NULL,

    CONSTRAINT pk_vote PRIMARY KEY (id),
    FOREIGN KEY (voter_id) REFERENCES users,
    FOREIGN KEY (quote_id) REFERENCES quotes,
    UNIQUE (voter_id, quote_id)
);